// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFPBUJYq67PKNSGizQKTuZip8sd_Pyook',
    appId: '1:427448119790:web:e146a399c470d2acdc5eff',
    messagingSenderId: '427448119790',
    projectId: 'sheltr-app',
    authDomain: 'sheltr-app.firebaseapp.com',
    storageBucket: 'sheltr-app.appspot.com',
    measurementId: 'G-SEKFEVKXS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA4a9-l5P0QXFYByZEPwOG3WHIxHNJC_A',
    appId: '1:427448119790:android:fd89bf26efa54a8bdc5eff',
    messagingSenderId: '427448119790',
    projectId: 'sheltr-app',
    storageBucket: 'sheltr-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3YFh13egK2315kOpWTBFgjDEuyNjtjEQ',
    appId: '1:427448119790:ios:342e3b83dff9f740dc5eff',
    messagingSenderId: '427448119790',
    projectId: 'sheltr-app',
    storageBucket: 'sheltr-app.appspot.com',
    androidClientId: '427448119790-6ff5brt2t026ocus3h462aub4tp4vn0o.apps.googleusercontent.com',
    iosClientId: '427448119790-rkp0s5m8vaqcus3q1qjb8qio1340uj4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.sheltrFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3YFh13egK2315kOpWTBFgjDEuyNjtjEQ',
    appId: '1:427448119790:ios:342e3b83dff9f740dc5eff',
    messagingSenderId: '427448119790',
    projectId: 'sheltr-app',
    storageBucket: 'sheltr-app.appspot.com',
    androidClientId: '427448119790-6ff5brt2t026ocus3h462aub4tp4vn0o.apps.googleusercontent.com',
    iosClientId: '427448119790-rkp0s5m8vaqcus3q1qjb8qio1340uj4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.sheltrFlutter',
  );
}
